---

- hosts: bacula-hosts-environment
  sudo: yes
  roles:
    - role: hostname

- hosts: bacula-hosts-environment
  sudo: yes
  tasks:
    - name: Ensure 127.0.1.1 loopback is not present in etc/hosts
      lineinfile:
        dest: "/etc/hosts"
        line: "127.0.1.1"
        regexp: "127.0.1.1"
        state: absent
    - name: Build hosts file
      lineinfile:
        dest: "/etc/hosts"
        regexp: '.*{{ item }}$'
        line: "{{item}}"
        state: present
      with_items:
      - "10.0.10.11 baculafd1.dev.lan baculafd1"
      - "10.0.10.21 baculasd1.dev.lan baculasd1"
      - "10.0.10.31 baculadir1.dev.lan baculadir1"

- hosts: bacula-dir-hosts
  sudo: yes
  vars_files:
    - vars/makevault-dir.yml
  roles:
    - role: mysql
    - role: bacula-web
    - role: percona_xtra
    - role: bacula-dir

- hosts: bacula-fd-hosts
  sudo: yes
  vars_files:
    - vars/makevault-fd.yml
  roles:
  - role: bacula-fd

- hosts: bacula-sd-hosts
  sudo: yes
  vars_files:
    - vars/makevault-sd.yml
  roles:
  - role: bacula-sd