---

bacula_sd_conf_dir: /etc/bacula
bacula_sd_conf_file: bacula-sd.conf
bacula_sd_conf_vars:
  storage:
    - Name: "{{ ansible_fqdn }}-sd"
    - SDPort: "9103"
    - WorkingDirectory: "/var/lib/bacula"
    - "Pid Directory": "/var/run/bacula"
    - "Maximum Concurrent Jobs": "20"
    - SDAddress: "127.0.0.1"
  director:
    - Name: "{{ ansible_fqdn }}-dir"
    # The following password field in quoted, so must pass those through
    - Password: "'password'"
  restricted_director:
    - Name: "{{ ansible_fqdn }}-mon"
    # The following password field in quoted, so must pass those through
    - Password: "'password'"
    - Monitor: "yes"
  devices:
    - name: "Device"
      vars:
        - Name: "FileStorage"
        - "Media Type": "File"
        - "Archive Device": "/nonexistant/path/to/file/archive/dir"
        - LabelMedia: "yes;"
        - "Random Access": "Yes;"
        - AutomaticMount: "yes;"
        - RemovableMedia: "no;"
        - AlwaysOpen: "no;"
  messages:
    - Name: "Standard"
    - director: "{{ ansible_fqdn }}-dir = all"